### ISSUE TITLE
CalendarPicker select time

### ISSUE THREAD

**Issue by kate2811** [edwardfhsiao/react-minimal-datetime-range#1]
Hi!

Is it possible to add a time picker to CalendarPicker like as in RangePicker?

**Comment by edwardfhsiao** [comment]
Sorry for the late reply, but do you need a time-select or a time-range-select?
I mean, are start time and end time both needed?

**Comment by edwardfhsiao** [comment]
Try v1.7.0
<CalendarPicker
 ...
 enableTimeSelection={true} // OPTIONAL
...
/>
